name: Terraform Workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.7  # Change to the version you want to use

    - name: Initialize Terraform
      run: terraform init
      
    - name: Validate Terraform Configuration
      run: terraform validate
      
    - name: Plan Terraform Deployment
      run: terraform plan -out=tfplan
      
    - name: Apply Terraform Changes
      run: terraform apply -auto-approve tfplan
